### ISSUE TITLE
NoPing (WinpkFilter) + Gen-2 Hyper-V Guest Network Adapter?

### ISSUE THREAD

**Issue by fragtion** [wiresock/ndisapi#15]
Hi

This is more of an issue report for Windows Packet Filter driver as opposed to ndisapi

I've been battling for a while to troubleshoot why NoPing (see https://noping.com/, which uses WinpkFilter driver) fails to work inside a Windows 10 guest VM on Hyper-V when using the default Network Adapter type on a "2nd Generation" Hyper-V VM

Then I figured out that if I downgrade the VM to a 1st Generation, and use a "Legacy Network Adapter" (which shows up in the VM as an "Intel 21140-Based PCI Fast Ethernet Adapter (Emulated)"), NoPing works fine

I guess any one of the following could be causing the failure?:
- Hyper-V's newer network adapter implementation for the VM, for which Microsoft would presumably be to blame?
or
- A problem with WinpkFilter driver when tied to this newer network adapter type?
or
- A problem with NoPing's implementation of WinpkFilter?

Unfortunately I wasn't able to figure this out on my own. Luckily I can work around it using the Legacy Network Adapter but hopefully this could get fixed before someone else falls into the same (time-consuming) trap !

Thanks & Regards
Dimitri

**Comment by wiresock** [comment]
Dear Dimitri,

I've just tested the latest version of Windows Packet Filter on a "Generation 2" Hyper-V VM with a Windows 10 21h2 guest, and it doesn't seem to have any noticeable issues. You can easily reproduce my test by downloading the latest release of Windows Packet Filter and the precompiled binaries. Please let me know if you get any misbehave with stock driver build on your hardware, so we could analyze the issue.

Yes, NoPing uses Windows Packet Filter drivers, but I don't know if they used the latest drivers in the build you tested, or if their software has any other side issues. If it can be helpful, I can contact NoPing for more details.

Hope it helps,
Vadim
