### ISSUE TITLE
Latest bin_tools dlls not working with C#

### ISSUE THREAD

**Issue by Nuklon** [wiresock/ndisapi#24]
The dlls from 3.4.8 aren't working correctly with C#'s dllimport (the previous versions were OK). All native calls return C#'s default.

**Comment by wiresock** [comment]
The package found at [this link](https://github.com/wiresock/ndisapi/releases/download/v3.4.8/tools_bin_x86_x64_vs2012.zip), which was built using Visual Studio 2012, contains the DLL that you had success with previously. It's puzzling why the DLLs built with Visual Studio 2022 do not work properly. I will need to conduct some research to pinpoint the exact problem and find a suitable solution.

**Comment by Nuklon** [comment]
Thanks, I'll give it a try later. Can you also add arm64 in that version?
I don't understand why the VS2022 version doesn't work. Usually .NET runtime gives some error that calling failed, but it's just doing its thing and returning the default (false for bool, 0 for int, etc).

**Comment by Nuklon** [comment]
If you have an update, I'm interested in it 😁

**Comment by wiresock** [comment]
The key distinction between the Visual Studio 2012 and Visual Studio 2022 projects centered around string encoding: the former utilized an ANSI string for the OpenFilterDriver parameter, while the latter required a UNICODE string. To address this incompatibility, I have [enhanced] (https://github.com/wiresock/ndisapi.net/commit/98a6b746b691ea46918b97fd65f219081f0500f6) the ndisapi.net project with a new optional string type parameter, which defaults to UNICODE, aligning with the modern builds of ndisapi.dll.

**Comment by Nuklon** [comment]
Interesting... but one question remains, why does OpenFilterDriver still return a "valid" handle with the wrong encoding?

**Comment by wiresock** [comment]
It returns an object that encapsulates the driver handle, irrespective of the driver's presence. To verify its validity, you can invoke the `IsDriverLoaded` method.

**Comment by Nuklon** [comment]
> It returns an object that encapsulates the driver handle, irrespective of the driver's presence. To verify its validity, you can invoke the `IsDriverLoaded` method.

That makes little sense. **Open**FilterDriver should return a valid handle only if there's a driver present with the given name. On your website: This function **opens driver object**, but if there's no driver, nothing can be opened?

**Comment by wiresock** [comment]
I don't usually use ndisapi.net in my projects, so I'm not entirely sure of the best approach. However, if you think it's more semantically appropriate to validate the OpenFilterDriver return object within the Open method itself, you're welcome to propose a change through a pull request.

**Comment by Nuklon** [comment]
> I don't usually use ndisapi.net in my projects, so I'm not entirely sure of the best approach. However, if you think it's more semantically appropriate to validate the OpenFilterDriver return object within the Open method itself, you're welcome to propose a change through a pull request.

I mean a behavior change for the DLL, or do you mean that as well?

**Comment by wiresock** [comment]
The OpenFilterDriver function inside the DLL is responsible for creating a new CNdisApi object and provides an opaque pointer in return. Given that this implementation has been in place for more than a decade, revising it seems unnecessary and might introduce unforeseen issues.
