### ISSUE TITLE
When installing the driver in win10 system, it will cause a short network disconnection

### ISSUE THREAD

**Issue by SYfirsthandsome** [wiresock/ndisapi#28]
When I install or uninstall the driver, I find that the network will be disconnected for a short time, and the computer network adapter will reconnect to verify, and this problem is currently only found on the win10 system computer, win11 is normal, is there a way to solve it?

**Comment by wiresock** [comment]
This is expected behavior because the network stack must rebind during the installation or removal of an NDIS filter driver. This behavior is also expected to affect Windows 11.
