### ISSUE TITLE
Packet loss in CS 2 when activating a tunnel

### ISSUE THREAD

**Issue by Ala2hhh** [wiresock/ndisapi#33]
Hi,

First I wanna say I love WireSock and the idea behind the project and I haven't tested it  much, however, I wanted to use it to tunnel discord traffic only and keep everything else normal.
when I activate the tunnel, even if CS 2 is included or not, I am experiencing packet loss up to 10% thus CS 2 is lagging.
it doesn't stay on 10% it goes down and back up, my guess is the filter is causing this issue regardless if CS 2 is filtered or not.
Also, this was tested on a capable machine of 32GB ddr5 and ryzen 7 7700 CPU

Thanks

**Comment by wiresock** [comment]
I believe this isn’t the right place to ask about the WireSock VPN Client, but I understand your issue. Currently, all traffic, whether it should be tunneled or not, is processed in user mode. We plan to improve this to enhance the network performance of non-tunneled apps, though this feature will likely be available in the paid version.
